import type { Product, Category, User, Order } from "@/src/shared/types"

export const mockUser: User = {
  id: "1",
  username: "user123",
  email: "user123@gmail.com",
  phone: "0912345678",
  gender: "male",
  dateOfBirth: "2004-01-01",
  avatar: "/anime-fan-avatar.png",
  isVIP: true,
  createdAt: "2024-01-01T00:00:00Z",
}

export const mockCategories: Category[] = [
  {
    id: "1",
    name: "Cosplay",
    slug: "cosplay",
    description: "Trang phục cosplay anime chất lượng cao",
    image: "/anime-cosplay.jpg",
  },
  {
    id: "2",
    name: "Figure",
    slug: "figure",
    description: "Mô hình nhân vật anime",
    image: "/anime-figure.jpg",
  },
  {
    id: "3",
    name: "Phụ kiện",
    slug: "accessories",
    description: "Phụ kiện cosplay và anime",
    image: "/anime-accessories.jpg",
  },
  {
    id: "4",
    name: "One Piece",
    slug: "one-piece",
    description: "Sản phẩm One Piece",
    image: "/anime-banner-2.jpg",
  },
  {
    id: "5",
    name: "Naruto",
    slug: "naruto",
    description: "Sản phẩm Naruto",
  },
  {
    id: "6",
    name: "Demon Slayer",
    slug: "demon-slayer",
    description: "Sản phẩm Kimetsu no Yaiba",
  },
]

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Trang phục Maomao",
    slug: "trang-phuc-maomao",
    description: "Trang phục cosplay Maomao Anime Nhật ký Apothecary Hanfu",
    price: 10990,
    categoryId: "1",
    images: [
      {
        id: "1",
        productId: "1",
        url: "/maomao-cosplay-costume.jpg",
        isPrimary: true,
        order: 1,
      },
    ],
    stock: 15,
    rating: 4.8,
    reviewCount: 24,
    createdAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "2",
    name: "Trang phục Luffy",
    slug: "trang-phuc-luffy",
    description: "Trang phục cosplay Monkey D Luffy One Piece",
    price: 365000,
    originalPrice: 450000,
    discount: 19,
    categoryId: "1",
    category: mockCategories[0],
    images: [
      {
        id: "2",
        productId: "2",
        url: "/luffy-cosplay-red-vest.jpg",
        isPrimary: true,
        order: 1,
      },
    ],
    stock: 8,
    rating: 4.9,
    reviewCount: 156,
    createdAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "3",
    name: "Thủy trụ của Kamado Tanjiro",
    slug: "thuy-tru-kamado-tanjiro",
    description: "Đạo cụ phát sáng anime cosplay thủng Thanh Gươm Diệt Quỷ",
    price: 250000,
    categoryId: "3",
    images: [
      {
        id: "3",
        productId: "3",
        url: "/tanjiro-sword-glowing.jpg",
        isPrimary: true,
        order: 1,
      },
    ],
    stock: 20,
    rating: 4.7,
    reviewCount: 89,
    createdAt: "2024-01-20T00:00:00Z",
  },
  {
    id: "4",
    name: "Trang phục Roronoa Zoro",
    slug: "trang-phuc-roronoa-zoro",
    description: "Trang phục cosplay Roronoa Zoro One Piece",
    price: 1270620,
    categoryId: "1",
    images: [
      {
        id: "4",
        productId: "4",
        url: "/zoro-cosplay-costume.jpg",
        isPrimary: true,
        order: 1,
      },
    ],
    stock: 5,
    rating: 4.9,
    reviewCount: 67,
    createdAt: "2024-01-12T00:00:00Z",
  },
  {
    id: "5",
    name: "Astray Blue Third Momoko",
    slug: "astray-blue-third-momoko",
    description: "Mô hình Gundam Astray Blue Third Momoko",
    price: 2500000,
    categoryId: "2",
    images: [
      {
        id: "5",
        productId: "5",
        url: "/gundam-astray-blue.jpg",
        isPrimary: true,
        order: 1,
      },
    ],
    stock: 3,
    rating: 5.0,
    reviewCount: 12,
    createdAt: "2024-01-18T00:00:00Z",
  },
  {
    id: "6",
    name: "Gundam RX-78",
    slug: "gundam-rx-78",
    description: "Mô hình Gundam RX-78 tỷ lệ 1/144",
    price: 250000,
    categoryId: "2",
    images: [
      {
        id: "6",
        productId: "6",
        url: "/gundam-rx78-model.jpg",
        isPrimary: true,
        order: 1,
      },
    ],
    stock: 12,
    rating: 4.6,
    reviewCount: 45,
    createdAt: "2024-01-08T00:00:00Z",
  },
  {
    id: "7",
    name: "Trang phục Violet Evergarden",
    slug: "trang-phuc-violet-evergarden",
    description: "Trang phục cosplay Violet Evergarden cao cấp",
    price: 2500000,
    categoryId: "1",
    images: [
      {
        id: "7",
        productId: "7",
        url: "/violet-evergarden-dress.jpg",
        isPrimary: true,
        order: 1,
      },
    ],
    stock: 4,
    rating: 4.9,
    reviewCount: 34,
    createdAt: "2024-01-22T00:00:00Z",
  },
  {
    id: "8",
    name: "Cosplay Naruto",
    slug: "cosplay-naruto",
    description: "Trang phục cosplay Naruto Uzumaki đầy đủ phụ kiện",
    price: 600000,
    categoryId: "1",
    images: [
      {
        id: "8",
        productId: "8",
        url: "/naruto-orange-costume.jpg",
        isPrimary: true,
        order: 1,
      },
    ],
    stock: 10,
    rating: 4.7,
    reviewCount: 98,
    createdAt: "2024-01-05T00:00:00Z",
  },
]

export const mockOrders: Order[] = [
  {
    id: "1",
    userId: "1",
    orderNumber: "ORD-2024-001",
    items: [
      {
        id: "1",
        orderId: "1",
        productId: "2",
        product: mockProducts[1],
        quantity: 1,
        price: 365000,
        total: 365000,
      },
      {
        id: "2",
        orderId: "1",
        productId: "4",
        product: mockProducts[3],
        quantity: 1,
        price: 1270620,
        total: 1270620,
      },
    ],
    subtotal: 1635620,
    shipping: 0,
    discount: 0,
    total: 1635620,
    status: "delivered",
    paymentMethod: "cod",
    shippingAddress: {
      id: "1",
      userId: "1",
      fullName: "David Laid",
      phone: "036933455633",
      address: "123 Đường Anime",
      city: "TP. Hồ Chí Minh",
      district: "Quận 1",
      isDefault: true,
    },
    createdAt: "2024-02-01T10:30:00Z",
    updatedAt: "2024-02-05T14:20:00Z",
  },
]
